### ISSUE TITLE
[Crash][1.16.4][MP] Crash when sorting? backpack

### ISSUE THREAD

**Issue by drakray** [Kevun1/Spice-of-Life-Potato-Edition#2]
**Description**
I was going through my large [backpack](https://www.curseforge.com/minecraft/mc-mods/useful-backpacks), tried sorting with a [sorting button](https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed), and crashed to desktop

**Crashlog**
https://pastebin.com/zY2XZNYC
<details><summary>Snippet</summary>

```
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.kevun1.solpotato.tracking.FoodList.getComplexity(FoodList.java:219) ~[solpotato:1.16.4-1.0.1c] {re:classloading}
	at com.kevun1.solpotato.tracking.FoodList.calculateDiversityContribution(FoodList.java:191) ~[solpotato:1.16.4-1.0.1c] {re:classloading}
	at com.kevun1.solpotato.client.TooltipHandler.onItemTooltip(TooltipHandler.java:44) ~[solpotato:1.16.4-1.0.1c] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_138_TooltipHandler_onItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:271) ~[forge:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:699) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.gui.screen.Screen.func_231151_a_(Screen.java:123) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230457_a_(Screen.java:118) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230459_a_(ContainerScreen.java:164) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.ContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at info.u_team.u_team_core.screen.FluidContainerScreen.func_230459_a_(FluidContainerScreen.java:63) ~[uteamcore:3.1.17.191] {re:classloading}
	at info.u_team.u_team_core.screen.UBasicContainerScreen.func_230430_a_(UBasicContainerScreen.java:26) ~[uteamcore:3.1.17.191] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:290) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.28.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.28.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
```

</details>

**To Reproduce**
Will try to reproduce

**Mod version and Forge version**
MC1.16.4
Forge 35.1.28
SoLPotato 1.0.1c

**Comment by drakray** [comment]
Seems to be a MouseOver thing, as trying to mouse over a food(berry from Undergarden that I just ate minutes ago), I crash instantly

Playing on dedicated server on Windows 10

**Comment by drakray** [comment]
Crash when looking at an Apple in Vanilla inventory too, after eating one, don't crash before eating

**Comment by Kevun1** [comment]
Thanks for the report. Right now it seems that this mod will always crash on a dedicated server.

I'll hopefully be rolling out a fix soon.

**Comment by Kevun1** [comment]
Version 1.0.2 should hopefully fix this. Reopen if you are still crashing
